pal/baremetal/target/RDN2/src/pal_exerciser.c
test_pool/exerciser/e007.c

- Replaced pal_mmio_write with multiple pal_mmio_writes to write 64bit DMA_BUS_ADDR register
- Replaced pal_mmio_read with multiple pal_mmio_read to read 64bit DMA_BUS_ADDR register

BSA: Fix for bug related to 32/64 bit access in pal_exerciser

---

test_pool/pcie/p087.c
val/include/acs_pcie_spec.h
val/src/sbsa_execute_test.c

- Resolves: https://github.com/ARM-software/sbsa-acs/issues/563
- Reads the number of EA entries from the capability header
- Iterates over all entries using their encoded sizes
- Checks the enable bit in each EA entry individually
- Adds supporting macros for EA entry size, count, and DWORD access

Iterate and validate all EA capability entries

---

test_pool/pe/pe016.c

Use test data instead of global for SVE2 test data The global will not be flushed from cache for non-0 PE causing a NULL dereference.
Reference bsa-acs PR: https://github.com/ARM-software/bsa-acs/pull/488
Contributor: @jbrasen

Use test data for SVE2 shared data

---

pal/uefi_dt/include/pal_uefi.h
pal/uefi_dt/src/pal_pe.c

Add cortex a78 pmu compatible string and align the secondary PE stack pointer to 16b for aarch64
Integrates some fixes from the ACPI version of this file.
Removes some unreachable ACPI code
Add support for an addition cortex pmu compatible string
Reference BSA PR: https://github.com/ARM-software/bsa-acs/pull/489
Contributor @jbrasen

Add cortex a78 pmu compatible string and align the secondary PE stack ptr to 16b

---

test_pool/pcie/p038.c
test_pool/pcie/p073.c

- Fixes: #28
- Having jump label inside loop bypassed the check for bounds.
- Moved it outside to prevent the sceanrio.
Change-Id: I5b64d03ec96703f26df79565a46c1e69dcabb2c7

fix(pcie): move next_bdf label to avoid array out of bound

---

pal/baremetal/target/RDN2/include/platform_override_fvp.h
pal/include/platform_override.h
val/include/pal_interface.h
val/src/acs_iovirt.c

Check if the SMMU base address is already mapped and map it if not. By default, 128 KB is mapped from the base. A platform override define is introduced to allow larger mappings if needed.
Fixes: #27

fix(iovirt): Add support for SMMU address mapping

---

val/src/AArch64/RasSupport.S

Closes: #48
Building ACS spits those messages:
RasSupport.iiii: Assembler messages:
RasSupport.iiii:66: Warning: specified register cannot be written to at operand 1 -- `msr erridr_el1,x0'
RasSupport.iiii:110: Warning: specified register cannot be written to at operand 1 -- `msr erxpfgf_el1,x0'
ERRIDR_EL1 register is RO
ERXPFGF_EL1 feels like RO as well

val: drop not used WriteErrIdr and WriteErrPfgf functions

---

test_pool/ras/ras005.c

- Prevents false error detection in subsequent loops
- intr_pending was not being reset to 1, leading to incorrect interrupt reporting
- Ensures accurate interrupt validation for each Node
Change-Id: I5a87d8233e42f565068aa19c92e9b3b161d9bd24

fix(ras005): Initialize intr_pending for every node

---

test_pool/mpam/mpam002.c
test_pool/mpam/mpam003.c
test_pool/mpam/mpam004.c
test_pool/mpam/mpam006.c

- Corrected typos in the print statements across multiple MPAM tests

fix(mpam): fix for typo in MPAM test prints

---

docs/pcie/ErrorInjection.md
docs/pcie/Exerciser.md
docs/pcie/PCIeConfigurableHierarchy.md

- Add poison mode documentation in ErrorInjection.md and expand details on DMA offset usage, transaction tracing, and BAR1 access in Exerciser.md.
- Update copyright years.

docs(pcie): update Exerciser and error injection docs

---

test_pool/pcie/p095.c

Log error if DMA address or length is zero due to inactive ATA command or scatterlist

Handle invalid DMA address scenario

---

test_pool/gic/its004.c

- Move initialization of curr_grp_its_id, curr_smmu_id, and curr_seg_num inside the loop to prevent incorrect reuse across BDF entries during ITS004 test execution.
Change-Id: I1ce7754ef9fbfa0137e153838bc5369dd4cedffb

fix: reinit ITS group tracking vars per device

---

val/src/acs_mmu.c
val/src/acs_peripherals.c
val/src/acs_timer_support.c

When verbose mode is enables some messages got joined with previous ones:
```
effective e2h : 0x0 TIMER_INFO: System Counter frequency :    1000 MHz
Address is already mapped SMMU_INFO: SMMU index 00 version     :    v3.1
Class code is 3800002 Peripheral: Num of Network ctrl      :    1
```
Now they are clean:
```
effective e2h : 0x0
TIMER_INFO: System Counter frequency :    1000 MHz
Address is already mapped
SMMU_INFO: SMMU index 00 version     :    v3.1
Class code is 3800002
Peripheral: Num of Network ctrl      :    1
```

val: add missing new lines

---

val/src/acs_pe_infra.c

Replace > with >= when comparing index to cur_pe_count so boundary indices advance to the next slot, preventing incorrect results or unintended ACS_STATUS_ERR.

Fix : PE index boundary check in val_get_pe_architecture

---

test_pool/pe/pe010.c
test_pool/pmu/pmu001.c

- Restore PMCR_EL0 after test.
- Prevent register check failure on reruns.

Restore PMCR_EL0 to fix BSA check

---

val/include/acs_pe.h
val/src/AArch64/PeRegSysSupport.S
val/src/acs_pe.c
val/src/acs_timer_support.c

- HCR_EL2 values are RES0 if EL2 is not present
- Remove the duplicate defination of HCR_EL2 reg read
Change-Id: I07c6bcd1d30f67ecb8b48a30ecad73520335bf67

Guard HCR_EL2 access with exception level check

---

test_pool/pcie/p002.c
val/include/acs_pcie.h
val/include/acs_pcie_spec.h

- Add support in PCIe test p002 to detect and skip SR-IOV VFs during ECAM region accessibility checks.
- Define helper macros for VF BDF derivation and SR-IOV capability parsing.
- Use val_memory_set for reset handling.
- Fixes #22 
Change-Id: I3f898914c1e55fa4bc8f5a59f528a20ad2c9a4a1

fix(p002): skip ECAM checks for virtual functions

---

apps/uefi/acs.h
pal/uefi_acpi/src/pal_pe.c
pal/uefi_dt/src/pal_pe.c

There are machines out there with more than 16 cpu cores. Test 16 fails on them:
PE Index = 63
Processor Family Not Found in SMBIOS Table
Skipped on PE -   17
B_PE_14
Checkpoint --  2                           : Result:  SKIPPED
This change bumps amount of supported cores to 1024. Should be enough for a while.
Closes: #77

SMBIOS: Handle 1024 cpu cores.

---

test_pool/pe/pe016.c

- Clarified invalid SVEver[3:0] case for Armv9
- Made comments wording consistent
- No functional code changes.

Improved wording and consistency of comments about SVE2 checks

---

apps/uefi/acs.h
apps/uefi/app.c
apps/uefi/bsa_main.c
apps/uefi/drtm_main.c
apps/uefi/mem_test_main.c
apps/uefi/mpam_main.c
apps/uefi/pc_bsa_main.c
apps/uefi/sbsa_main.c
apps/uefi/sbsa_nist_main.c
apps/uefi/unified_main.c

fix(uefi): prevent tests from running on -h/-help
- Ensure `-h` and `-help` options only display usage help without triggering test execution.
- Replace ambiguous return codes with `ACS_PARSE_SKIP_RUN` for consistent command parsing behavior.
- Standardize handling of invalid parameters across all UEFI test apps
Fixes: #75

Prevent tests from running on -h/-help

---

test_pool/exerciser/e015.c
test_pool/pcie/p036.c
test_pool/pcie/p071.c
val/include/acs_pcie.h
val/include/acs_pcie_spec.h
val/src/acs_pcie.c

- Resolves #113 
- Enable/disable DCTL2.AFE and read back; fail if write doesn’t take effect.
- Bug fixes and enhancements

Validate ARI forwarding and AFE writes
